var all_lessons = ['L1', 'L2', 'L3', 'L4', 'L5', 'Numbers'];

var characters = 
  {
    'L1' : [
      //character  pinyin       type   meaning
      ['nǐ',       '你',           'Pr',    'you'],
      ['hǎo',      '好',           'A',     'good; well; fine; OK'],
      ['ma',       '吗',           'QPt',   'interrogative particle for yes-no answer'],
      ['wǒ',       '我',           'Pr',    'I; me'],
      ['hěn',      '很',           'Adv',   'very'],
      ['ne',       '呢',           'MdPt',  'modal particle for elliptical questions'],
      ['yě',       '也',           'Adv',   'too; also']
    ],             
    'L2' : [       
      ['máng',     '忙',           'A',    'busy'],
      ['ma',       '吗',           'QPt',  'interrogative particle for yes-no answer'],
      ['bàba',     '爸爸',          'N',    'dad'],
      ['māma',     '妈妈',          'N',    'mom'],
      ['tāmen',    '他们',          'Pr',   'they, them'],
      ['tā',       '他',           'Pr',   'he, him'],
      ['men',      '们',           'Suf',  'used after pronouns or some nouns to denote plurality'],
      ['dōu',      '都',           'Adv',  'both; all'],
      ['bù',       '不',           'Adv',  'not; no'],
      ['nán',      '男',           'A',    'male'],
      ['péngyou',  '朋友',          'A',    'friend'],
      ['ne',       '呢',           'MdPt', 'modal particle for elliptical questions'],
      ['gēge',     '哥哥',          'N',    'elder brother'],
      ['yào',      '要',           'V',    'to want'],
      ['kāfēi',    '咖啡',          'N',    'coffee'],
      ['dìdi',     '弟弟',          'N',    'younger brother'],
      ['wǒmen',    '我们',          'Pr',   'we; us'],
      ['hē',       '喝',           'V',    'to drink'],
    ],
    'L3' : [
      ['tā',       '她',           'Pr',    'she; her'],
      ['shì',      '是',           'V',     'to be; is'],
      ['nǎ',       '哪',           'QPr',   'which'],
      ['guó',      '国',           'N',     'country; nation'],
      ['rén',      '人',           'N',     'person; people'],
      ['nà',       '那',           'Pr',    'that'],
      ['shéi',     '谁',           'QPr',   'who; whom'],
      ['lǎoshi',   '老师',          'N',     'teacher'],
      ['dōu',      '都',           'Adv',   'both; all'],
      ['nín',      '您',           'Pr',    'polite form of you'],
      ['zhè',      '这',           'Pr',    'this'],
      ['tā',       '他',           'Pr',    'he; him'],
      ['nǐ',       '你',           'Pr',    'you'],
      ['yīshēng',  '医生',          'N',     'doctor; physician'],
      
    ],
    'L4' : [
     ['rènshi',    '认识',          'V',     'to know (someone)'],
     ['gāoxìng',   '高兴',          'A',     'happy; pleased'],
     ['kěyǐ',      '可以',          'OpV',   'may (asking permission)'],
     ['jìnlai',    '进来',          'VC',    'to come in'],
     ['jìn',       '进',           'V',     'to enter'],
     ['lái',       '来',           'V',     'to come'],
     ['qǐng',      '请',           'V',     'please'],
     ['nín',       '您',           'Pr',    'you (polite)'],
     ['péngyou',   '朋友',          'N',     'friend'],
     ['qǐngwèn',   '请问',          'V',     'May I ask...?'],
     ['wèn',       '问',           'V',     'to ask'],
     ['guìxìng',   '贵姓',          'IE',    'what is your honorable surname?'],
     ['xìng',      '性',           'V/N',   'surname'],
     ['jiào',      '叫',           'V',     'to be called'],
     ['xiānsheng', '先生',          'N',     'Mr.'],
     ['yǔyán',     '语言',          'N',     'language'],
     ['xuéyuàn',   '学院',          'N',     'institute'],
     ['de',        '的',           'Pt',    'a posessive modifying particle'],
     ['xuésheng',  '学生',          'N',     'student'],
     ['shénme',    '什么',          'QPt',   'what'],
     ['xuéxí',     '学习',          'V',     'to learn; to study'],
     ['Hànyǔ',     '汉语',          'N',     'Chinese language'],
     ['Yīngguó',   '英国',          'PN',    'England'],
     ['Měiguó',    '美国',          'PN',    'America'],

    ],
    'L5' : [
     ['zài',       '在',           'V',    'to be (here, there, in, on, at)'],
     ['nǎr',       '哪儿',          'QPr',  'where'],
     ['qǐngwèn',   '请问',          'V',    'May I ask'],
     ['wèn',       '问',           'V',    'to ask'],
     ['zhè',       '这',           'Pr',   'this'],
     ['sùshè',     '宿舍',          'N',    'dormitory'],
     ['nǚ',        '女',           'A',    'female'],
     ['xuésheng',  '学生',          'N',    'student'],
     ['jìn',       '进',           'V',    'to enter'],
     ['zuò',       '坐',           'V',    'to sit'],
     ['xièxie',    '谢谢',          'V',    'to thank'],
     ['duìbuqǐ',   '对不起',         'IE',   'I am sorry'],
     ['wǒ',        '我',           'Pr',   'I; me'],
     ['zhīdao',    '知道',          'V',    'to know'],
     ['méi guānxi','没关系',         'IE',   'never mind; it doesnt matter'],
     ['hǎo',       '好',           'A',    'good; well; fine; OK'],
     ['zàijiàn',   '再见',          'IE',   'good-bye'],
     ['zài',       '再',           'Adv',  'again'],
     ['xiǎojiě',   '小姐',          'N',    'Miss; young lady'],
     ['hào',       '号',           'N',    'number'],
     ['búyòng',    '不用',          'Adv',  'need not'],
     ['zhèr',      '这儿',          'Pr',   'here'],
     ['wǎn',       '晚',           'A',    'late'],
     ['le',        '了',           'Pt',   'modal aspect to show completeness'],
    ],
    'Numbers' : [
     ['líng',      '0',           'Nu',    '0'],
     ['yī',        '一',           'Nu',    '1'],
     ['èr',        '二',           'Nu',    '2'],
     ['sān',       '三',           'Nu',    '3'],
     ['sì',        '四',           'Nu',    '4'],
     ['wǔ',        '五',           'Nu',    '5'],
     ['liù',       '六',           'Nu',    '6'],
     ['qī',        '七',           'Nu',    '7'],
     ['bā',        '八',           'Nu',    '8'],
     ['jiǔ',       '九',           'Nu',    '9'],
     ['shí',       '十',           'Nu',    '10'],
    ],

  };